# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_xelatex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Latexmk with XeLatex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: thesis
          path: thesis.pdf
        
